global:
  scrape_interval:  5s
  scrape_timeout: 3s
  evaluation_interval:  5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql57-exporter:9104']

  - job_name: 'my-exporter'
    static_configs:
      - targets: ['app:8000']
